spring:
  application:
    name: Eureka2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/


