eureka:
  instance:
    #eureka客户端endpoints, 用于告知eureka服务端
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/eureka/,http://eureka2:8762/eureka/eureka/,
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
